namespace MauiDotnetPublishBug.Common.Settings
{
    /// <summary>
    /// Service used to store and retrieve settings' values.
    /// </summary>
    public interface ISettingsManager
    {
        #region Methods

        #region Public

        /// <summary>
        /// Clear all stored settings.
        /// </summary>
        public void Clear();

        /// <summary>
        /// Get the <see cref="DateTime"/> that the random <see cref="Color"/> was generated at.
        /// The random <see cref="Color"/> can be set with <see cref="SetRandomColour"/>, and
        /// retrieved with <see cref="GetRandomColour"/>.
        /// <para>
        /// This will return <see cref="DateTime.MinValue"/> if the setting has not yet been set.
        /// </para>
        /// </summary>
        /// <returns>
        /// The <see cref="DateTime"/> that the random <see cref="Color"/> was generated at.
        /// </returns>
        public DateTime GetColourGenerationTime();

        /// <summary>
        /// Get the stored random <see cref="Color"/>.
        /// <para>
        /// This will return <see langword="null" /> if the setting has not yet been set.
        /// </para>
        /// </summary>
        /// <returns>
        /// The random <see cref="Color"/> generated by the app.
        /// </returns>
        public Color? GetRandomColour();

        /// <summary>
        /// Set <see cref="DateTime"/> that the random <see cref="Color"/> was generated at. The
        /// random <see cref="Color"/> can be set with <see cref="SetRandomColour"/>, and retrieved
        /// with <see cref="GetRandomColour"/>.
        /// </summary>
        /// <param name="generationTime">
        /// The <see cref="DateTime"/> that the random <see cref="Color"/> was generated at.
        /// </param>
        public void SetColourGenerationTime(DateTime generationTime);

        /// <summary>
        /// Set the stored random <see cref="Color"/>.
        /// </summary>
        /// <param name="colour">
        /// The random <see cref="Color"/> that was generated by the app.
        /// </param>
        public void SetRandomColour(Color colour);

        #endregion

        #endregion
    }
}
