name: CI Build

# Configure the triggers for the workflow.
on:
  # Automatically run when code or workflow changes are pushed to main.
  push:
    branches: [ main ]
    paths:
      - "src/"               # Run the workflow if the src is updated.
      - ".github/workflows/" # Run the workflow if it is updated.
      - "!**/*.md"           # Do not run the workflow for updated docs.
      - "!**/*.gitignore"    # Do not run the workflow for updated .gitignore.
  # Automatically run the workflow when a PR is opened targeting main.
  pull_request:
    branches: [ main ]
  # Allow the workflow to be run manually.
  workflow_dispatch:

# Set the level of access of the GitHub API token for this workflow.
permissions:
  contents: read # Allow the workflow to read the repo contents.

# Define environmental variables.
env:
  DOTNET_NOLOGO: true     # Disable the .NET CLI banner to reduce output noise.
  DOTNET_VERSION: "9.0.x" # Use the latest .NET Core 9 version.
  XCODE_VERSION: "16.3"   # Xcode 16.3 is required for Microsoft.iOS 18.4.9288.

# Define jobs for the workflow.
jobs:
  build-android:
    runs-on: windows-2022
    name: Android Build
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore src/MauiDotnetPublishBug.App/MauiDotnetPublishBug.App.csproj

      - name: Build MAUI Android
        run: dotnet publish src/MauiDotnetPublishBug.App/MauiDotnetPublishBug.App.csproj -c Release -f net9.0-android --no-restore

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mauidotnetpublishbug-android-ci-build
          path: src/MauiDotnetPublishBug.App/bin/Release/net9.0-android/*Signed.a*

  build-ios:
    # macos-15-large would technically be the equivalent to a MS-hosted macos-15
    # runner image on Azure Pipelines, but that isn't available as standard for
    # non-enterprise plans. I'll see what I can do with the arm64 macOS images
    # instead...
    runs-on: macos-15
    name: iOS Build
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore src/MauiDotnetPublishBug.App/MauiDotnetPublishBug.App.csproj

      # In our actual pipeline, we use dotnet publish. However, that requires a
      # provisioning profile and signing certificate which I don't have for this
      # repo. Instead, I've tried to use dotnet build to see if it exhibits the
      # same behaviour.
      - name: Build MAUI iOS
        run: dotnet build src/MauiDotnetPublishBug.App/MauiDotnetPublishBug.App.csproj -c Release -f net9.0-ios --no-restore /p:buildForSimulator=True /p:packageApp=True /p:ArchiveOnBuild=False

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mauidotnetpublishbug-ios-ci-build
          path: src/MauiDotnetPublishBug.App/bin/Release/net9.0-ios/iossimulator-x64/**/*.ipa
